# Generated by Django 5.0.7 on 2024-07-27 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_contact_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_time',
        ),
        migrations.AddField(
            model_name='contact',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
